In [1]:
import pygadgetreader
from pygadgetreader import *

In [2]:
import numpy as np
import pandas as pd

In [3]:
readheader('lcdm_snap002_cdm','header')

{'npartThisFile': array([     0, 262144,      0,      0,      0,      0], dtype=uint32),
 'npartTotal': array([     0, 262144,      0,      0,      0,      0], dtype=uint32),
 'npartTotalHW': array([0, 0, 0, 0, 0, 0], dtype=uint32),
 'ngas': 0,
 'ndm': 262144,
 'ndisk': 0,
 'nbulge': 0,
 'nstar': 0,
 'nbndry': 0,
 'massTable': array([   0.       , 1119.6422402,    0.       ,    0.       ,
           0.       ,    0.       ]),
 'time': 1.0,
 'nfiles': 1,
 'redshift': 0.0,
 'boxsize': 320000.0,
 'O0': 0.3228269102249944,
 'Ol': 0.6771730897750057,
 'h': 0.67,
 'flag_cooling': 0,
 'flag_sfr': 0,
 'flag_fb': 0,
 'flag_fh2': 0,
 'flag_age': 0,
 'flag_metals': 0,
 'flag_potential': 0,
 'flag_delaytime': 0,
 'flag_tmax': 0,
 'rhocrit': 8.432254544043031e-30}

In [4]:
vel = readsnap('n1lcdm_snap002_cdm','vel','dm')
vx = vel[:,0].tolist()
vy = vel[:,1].tolist()
vz = vel[:,2].tolist()
mass = readsnap('n1lcdm_snap002_cdm','mass','dm').tolist()
particle_id = readsnap('n1lcdm_snap002_cdm','pid','dm').tolist()
position = readsnap('n1lcdm_snap002_cdm','pos','dm')
x = position[:,0].tolist()
y = position[:,1].tolist()
z = position[:,2].tolist()

Returning DM    Velocities
Returning DM    Mass
Returning DM    Particle IDs
Returning DM    Positions


In [5]:
data = {'id': particle_id,
        'x': x,
        'y': y,
        'z': z,
        'vx': vx,
        'vy': vy,
        'vz': vz,
        'mass': mass}
dfn = DataFrame(data)

NameError: name 'DataFrame' is not defined

In [ ]:
dfn

id              x              y  ...          vy          vz         mass
0         58    9242.752930    3242.119385  ... -218.829803 -180.311935  1017.058838
1         67   20151.337891    2354.641602  ... -243.747452  -75.132721  1017.058838
2         68   27274.539062    2380.892822  ... -242.251205  -11.595575  1017.058838
3        123   30789.302734    2577.025879  ... -237.445831  -14.650444  1017.058838
4        124   33851.128906    3291.046631  ... -210.843491  -62.302464  1017.058838
...      ...            ...            ...  ...         ...         ...          ...
262139   896  281750.312500  315163.906250  ... -364.425781 -285.827728  1017.058838
262140   966  301999.125000  315704.718750  ... -385.332825 -464.576080  1017.058838
262141  1017  305009.437500  316931.437500  ... -327.499115 -480.226379  1017.058838
262142  1022  307979.625000  317198.781250  ... -304.486786 -487.300415  1017.058838
262143     1  312456.468750  316589.656250  ... -321.869659 -465.636719  1017.058838

[262144 rows x 8 columns]

In [ ]:
dfn.to_csv('n1lcdm_snap002_cdm.csv',index=False)

In [ ]:
df['mass'].unique()

array([1119.64221191])

In [ ]:
dfn['mass'].unique()

array([1017.05883789])

In [ ]:
df['mass'].unique()-dfn['mass'].unique()

array([102.58337402])

In [ ]:
import numpy as np
f = open('0halos_0.00.ascii', "r", encoding="ascii")
df0 = pd.read_csv(f, sep=' ', skiprows=np.arange(1,19), skipinitialspace=True)

In [ ]:
df0

#id  num_p          mvir    mbound_vir        rvir        vmax  \
0          0   1229  2.285000e+12  2.285000e+12  266.175812  192.383438   
1          1   1868  3.149000e+12  3.149000e+12  296.199280  213.891830   
2          2   1209  2.154000e+12  2.154000e+12  260.980804  188.649231   
3          3    354  1.129000e+12  1.017000e+12  203.211121  146.879105   
4          4    589  1.069000e+12  1.069000e+12  206.613525  149.664597   
...      ...    ...           ...           ...         ...         ...   
11356  11356   1864  4.737000e+12  3.308000e+12  301.089050  217.406693   
11357  11357   2126  7.553000e+12  5.314000e+12  352.640259  254.605698   
11358  11358   4747  4.142000e+13  4.029000e+13  692.770142  500.142426   
11359  11359   9218  2.478000e+13  2.475000e+13  588.885254  425.206879   
11360  11360   2705  7.156000e+12  6.806000e+12  382.971344  277.538452   

            rvmax        vrms           x           y  ...   Rs_Klypin  \
0      263.027893  152.358643    1.010648   14.999656  ...  110.059952   
1      295.796997  185.898254    1.821474    7.740228  ...  130.057281   
2      231.256943  158.219604    9.522031    0.387198  ...  107.347298   
3      202.190475  167.104691    9.188568    8.955805  ...   83.898079   
4      204.707260  107.549843    9.063432   10.639209  ...   78.825623   
...           ...         ...         ...         ...  ...         ...   
11356  300.488586  291.189697  151.548782  154.983948  ...  133.339661   
11357  352.587433  307.261017  152.225204  155.182053  ...  158.471909   
11358  692.767395  487.734406  151.720032  154.971680  ...  318.870911   
11359  588.576355  400.447205  149.542694  158.784988  ...  261.443329   
11360  354.118378  307.876404  149.183105  159.262329  ...  144.270416   

          T/|U|  M_pe_Behroozi   M_pe_Diemer  Halfmass_Radius     idx    i_so  \
0      0.508824   2.840081e+12  4.346268e+12       166.629425     171      -1   
1      0.588591   4.093968e+12  6.459264e+12       173.263321     278      -1   
2      0.585476   2.622575e+12  5.174519e+12       153.619080     323      -1   
3      2.092456   1.510520e+12  3.050588e+12       131.272751     348      -1   
4      0.505239   1.281925e+12  2.077461e+12       121.033386     412      -1   
...         ...            ...           ...              ...     ...     ...   
11356  1.499362   3.882662e+12  5.600945e+12       194.957626  718130  718157   
11357  1.212535   7.928112e+12  1.223515e+13       261.246918  718135  718157   
11358  0.888558   4.847936e+13  7.241319e+13       454.122131  718157  717803   
11359  0.636187   2.836733e+13  4.478569e+13       382.657227  718256      -1   
11360  0.891436   6.825476e+12  8.512124e+12       233.820236  718277  718256   

       i_ph  num_cp       mmetric  
0        -1    1591  1.000000e+10  
1        -1    2363  1.000000e+10  
2        -1    1930  1.000000e+10  
3        -1    1334  1.000000e+10  
4        -1     773  1.000000e+10  
...     ...     ...           ...  
11356    -1    3182  1.869524e+00  
11357    -1    6118  2.385096e+00  
11358    -1   29334  1.268642e+01  
11359    -1   17260  1.000000e+10  
11360    -1    3655  1.701676e+00  

[11361 rows x 54 columns]

In [ ]:
(df0['#id'].unique()).shape

(11361,)

In [ ]:
list(df0)

['num_p',
 'mvir',
 'mbound_vir',
 'rvir',
 'vmax',
 'rvmax',
 'vrms',
 'x',
 'y',
 'z',
 'vx',
 'vy',
 'vz',
 'Jx',
 'Jy',
 'Jz',
 'E',
 'Spin',
 'PosUncertainty',
 'VelUncertainty',
 'bulk_vx',
 'bulk_vy',
 'bulk_vz',
 'BulkVelUnc',
 'n_core',
 'm200b',
 'm200c',
 'm500c',
 'm2500c',
 'Xoff',
 'Voff',
 'spin_bullock',
 'b_to_a',
 'c_to_a',
 'A[x]',
 'A[y]',
 'A[z]',
 'b_to_a(500c)',
 'c_to_a(500c)',
 'A[x](500c)',
 'A[y](500c)',
 'A[z](500c)',
 'Rs',
 'Rs_Klypin',
 'T/|U|',
 'M_pe_Behroozi',
 'M_pe_Diemer',
 'Halfmass_Radius',
 'idx',
 'i_so',
 'i_ph',
 'num_cp',
 'mmetric']

In [ ]:
f = open('1halos_0.00.ascii', "r", encoding="ascii")
df1 = pd.read_csv(f, sep=' ', skiprows=np.arange(1,19), skipinitialspace=True).drop(['#id'],axis=1)

In [ ]:
df1

num_p          mvir    mbound_vir  ...  i_ph  num_cp       mmetric
0      1601  1.934000e+12  1.934000e+12  ...    -1    2149  1.000000e+10
1       715  1.554000e+12  1.554000e+12  ...    -1    1088  2.035243e+00
2      1442  4.930000e+12  4.930000e+12  ...    -1    3624  1.000000e+10
3      1182  1.088000e+12  1.088000e+12  ...    -1    1778  1.000000e+10
4       442  1.106000e+12  1.106000e+12  ...    -1    1032  4.822279e+00
...     ...           ...           ...  ...   ...     ...           ...
9669   1097  1.508000e+12  1.493000e+12  ...    -1    1223  1.238900e+00
9670   1849  5.095000e+12  5.042000e+12  ...    -1    6372  7.127546e+00
9671   7256  2.065000e+13  2.062000e+13  ...    -1   12967  1.000000e+10
9672   1939  3.402000e+12  3.189000e+12  ...    -1    2285  2.379352e+00
9673   1100  9.845000e+11  9.845000e+11  ...    -1    1745  1.000000e+10

[9674 rows x 53 columns]